### ISSUE TITLE
tag click not updating work/blog lists

### ISSUE THREAD

**Issue by nbriz** [brangerbriz/www#21]
seems initial tag click doesn't update view but does update URL/path/route

**Comment by pbriz** [comment]
I'm not sure if you did something to this, but its working fine now!

**Comment by pbriz** [comment]
looked into it further and noticed that it does seem to still happen but the behavior has changed a bit. When a word is partially typed in and then the dropdown is clicked using the mouse, the url path is changing and the page seems to update based on the url. Here is an example of what is happening:

type in "mob" into the search bar
"mobile" appears in the dropdown
"mobile" is selected using the mouse
"mob" is automatically replaced in the search field with "undefined"
the url changes to "search?tags=undefined"
"sorry..." error message appears in results area

now type in "mo" in search field
select "mobile" from dropdown with the mouse 
the url changes to "search?tags=mobile"
results area shows correct results

now type in "mobil" in search field
select "mobile" from dropdown with the mouse 
"mobil" is automatically replaced in the search field with "undefined"
the url changes to "search?tags=undefined"
"sorry..." error message appears in results area

**Comment by nbriz** [comment]
seems this happens if u start searching for something, example "mo" then click on the tag that pops up underneath in the autocomplete list (ex: "mobile" ) then if u hit enter again (with the word "mobile" still in the input field) the URL says "search?tags=undefined"
